---
title: "Freezerworks Aliquot Report"
author: "Dominick Lemas"
date: "March 23, 2019"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include = FALSE}
# open data
work.dir=paste0(Sys.getenv("USERPROFILE"),"\\Dropbox (UFL)\\02_Projects\\FREEZERWORKS\\BEACH_Study\\Export\\")
data.dir=paste0(Sys.getenv("USERPROFILE"),"\\Dropbox (UFL)\\02_Projects\\FREEZERWORKS\\BEACH_Study\\Export\\")

library(tidyr)
library(tidyverse)
library(dplyr)

# Read Data
data.file.name="BEACH_DATA_EXPORT_11APR19.csv";data.file.name
data.file.path=paste0(data.dir,"\\",data.file.name);data.file.path
freezer<- read.csv(data.file.path);

# look at data
dat=freezer
head(dat); str(dat); names(dat)
```
## Coding Mistakes

### "3rd Trimester" when should be "3rd_trimester"  

```{r, echo = FALSE}
  visit.3t=dat%>%
    filter(clinic_visit=="3rd Trimester")
  print(as.character(visit.3t$Participant_ID))
```
### "2_weeks" when should be "2_week"
```{r,echo = FALSE}
visit.2wk=dat%>%
  filter(clinic_visit=="2_weeks")
  print(as.character(visit.2wk$Participant_ID))
```

```{r, include = FALSE}
# set the order of redcap_events
df <- dat %>% 
  mutate(clinic_visit = factor(clinic_visit, 
                              levels = c("3rd_trimester", 
                                               "2_week", 
                                               "2_months",
                                               "6_months",
                                               "12_months")),
         Clinic.visit.date=as.Date(Clinic.visit.date,"%m/%d/%Y"),
        part_id_link=gsub("A","",Participant_ID),
        part_id_link=gsub("B$","",part_id_link))
```
## Explore the Data

### how many mom-baby pairs with samples by clinic visit?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
  df%>%
    group_by(clinic_visit)%>%
    summarize(count=n_distinct(part_id_link))
```

### how many aliquots per mom-baby pair?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
part_count=df %>%
  group_by(part_id_link) %>%
  summarize(count=n_distinct(crc_specimen_barcode))
  mean(part_count$count) # 43.9 tubes
```
### aliquot count for each sample types?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
df %>%
  group_by(Aliquot.Type) %>%
  summarize(count=n_distinct(crc_specimen_barcode))
```
### how many aliquots per tube type?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
df %>%
  group_by(Freezer.Section) %>%
  summarize(count=n_distinct(crc_specimen_barcode))
```

```{r, include = FALSE}
# output data for import to redcap
redcap=df %>%
  select(Participant_ID,clinic_visit,Clinic.visit.date,Mom_Baby,Aliquot.Type,crc_specimen_barcode,crc_specimen_number,
         tube.type,Aliquot.Number) %>%
  rename(test_id=Participant_ID, 
         biosample_study_visit=clinic_visit,
         biosample_collection_date=Clinic.visit.date,
         biosample_mom_baby=Mom_Baby,
         biosample_aliquot_type=Aliquot.Type,
         crc_specimen_barcode=crc_specimen_barcode,
         crc_specimen_number=crc_specimen_number,
         biosample_tube_type=tube.type,
         biosample_aliquot_numb=Aliquot.Number)%>%
  mutate(redcap_event_name=NA,
         redcap_repeat_instrument="biological_specimen_collection")%>%
  arrange(test_id,biosample_study_visit,biosample_collection_date,biosample_aliquot_type)%>%
  #group_by(test_id,biosample_study_visit) %>% 
  mutate(redcap_repeat_instance=row_number())%>%
  select(test_id,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,everything())%>%
  mutate(redcap_event_name=case_when(biosample_study_visit=="3rd_trimester" ~ "third_trimester_arm_1",
                                     biosample_study_visit=="2_week" ~ "two_week_arm_1",
                                     biosample_study_visit=="2_months" ~ "two_month_arm_1",
                                     biosample_study_visit=="6_months" ~ "six_month_arm_1",
                                     biosample_study_visit=="12_months" ~ "twelve_month_arm_1"))%>%
  mutate(redcap_event_name = factor(redcap_event_name, 
                               levels = c("third_trimester_arm_1", 
                                          "two_week_arm_1", 
                                          "two_month_arm_1",
                                          "six_month_arm_1",
                                          "twelve_month_arm_1")))
```
### how many aliquots by clinic visit?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
table(redcap$redcap_event_name)
```
### how many aliquots have barcode but DO NOT have clinic visit info?
```{r,echo = FALSE,message = FALSE,warning = FALSE}
clinic.missing=redcap%>%
    filter(is.na(redcap_event_name)==T)
  print(length(as.character(clinic.missing$crc_specimen_barcode)))
```


```{r, include = FALSE}
export=redcap%>%
  mutate(biosample_collection_date=format(biosample_collection_date, "%m/%d/%Y"))%>%
  ungroup()%>%
  mutate(biosample_study_visit=recode(biosample_study_visit, 
                     "3rd_trimester"="1", 
                     "2_week"="2",
                     "2_months"="3",
                     "6_months"="4",
                     "12_months"="5"),
         biosample_mom_baby=recode(biosample_mom_baby,
                      "mom"="0",
                      "baby"="1"),
         biosample_aliquot_type=recode(biosample_aliquot_type,
                      "plasma"="1",
                      "urine"="2",
                      "saliva"="3",
                      "milk- skim"="4",
                      "milk- whole"="5",
                      "milk-lipid"="6",
                      "stool"="7",
                      "vaginal"="8",
                      "blood"="9",
                      "formula"="10"),
         biosample_tube_type=recode(biosample_tube_type,
                      "2ml"="1",
                      "ez sample"="2",
                      "vaginal vial"="3",
                      "5ml"="4",
                      "tiny"="5",
                      "blood card"="6",
                      "other"="7",
                      "15ml"="8",
                      "saliva tube"="9",
                      "50ml"="10"))
# replace NA with blanks
df <- sapply(export, as.character)
df[is.na(df)] <- " "
df1=as.data.frame(df)

# export test data: BLS001A
redcap.bls001=df1%>%
  filter(test_id=="BLS001A")%>%
write_csv(path =paste0(work.dir,"redcap.bls001.csv",na = ""))
```
