---
title: "Missing_data dynamic"
author: "Luran M."
date: "June 20, 2019"
output: html_document
---


```{r echo=FALSE, results="hide", include=F}

library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)

#Create path to and api link to RedCaps
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)


# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)

# crc variables
#fields <- exportFieldNames(rcon)
#crc variables for 3rd trimester visit
desired_fields_triHU=c("mom3t_delivery_location",
                       "mom3t_breast_surg",
                       "mom3t_baby_sex",
                       "mom3t_prepreg_bmi",
                       "infant_crc_wt_kg",
                       "mom3t_folic")
desired_fields_triHU2=c("mom3t_delivery_location",
                        "mom3t_meds_rx_14d",
                        "mom3t_meds_name",
                        "mom3t_meds_length",
                        "mom3t_insurance",
                        "mom3t_insurance_other",
                        "mom3t_birth_ctrl",
                        "mom3t_birth_ctrl_other",
                        "mom3t_preg_no_reason",
                        "mom3t_preg_no_reason_other",
                        "mom3t_fertility_tr",
                        "mom3t_medical_tx_other",
                        "mom3t_preg_insur",
                        "mom3t_preg_insur_other",
                        "mom3t_baby_race","mom3t_race",
                        "mom3t_healthcare_services",
                        "mom3t_language_other",
                        "mom3t_country_other",
                        "mom3t_usa_yr")
# crc variables for the 2 week visit 
desired_fields_2wkHU=c("mom2wk_delivery_date",
                       "inf2wk_delivery_location",
                       "inf2wk_sex",
                       "mom2wk_baby_weight_pounds",
                       "inf2wk_baby_weight_today")

# combine desired fields and import test_id and redcap_event_name
desired_fields_all=c(desired_fields_triHU2,desired_fields_2wkHU,"test_id","redcap_event_name")

# events to retain
#exportEvents(rcon)
events_to_retain  <- c("third_trimester_arm_1", "two_week_arm_1", "two_month_arm_1")

# list of instruments
#exportInstruments(rcon)
Instruments_to_retain <- c("health_update_3rd_trimester_v5082518","clinical_health_update_2wk_v4_042218",
                           "clinical_health_update_2mo_to_12mo_v3_022118","infant_feeding_questionnaire_2_weeks_v3_042218",
                           "infant_feeding_questionnaire_2mo_to_12mo_v3_022118")

# list of events
#exportEvents(rcon)

# list records
#exportRecords(rcon)

# export field names
#exportFieldNames(rcon)

# consented records
consent.records.v1=c("BLS001A","BLS002A","BLS003A")

# pull data
ds_some_rows_v1 <- redcap_read(
  batch_size=300,
  records= consent.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields_all,
  events     = events_to_retain,
  )$data

head(ds_some_rows_v1)
```





```{r}
#chart of Delivery location question at 3rd trimester   
DeliveryLocation_tri <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,mom3t_delivery_location)%>%
  arrange(test_id,redcap_event_name)%>%
  filter(redcap_event_name == "third_trimester_arm_1")


#Talbe of participants who responsed to the question

DeliveryLocation_tri_pop<-filter(DeliveryLocation_tri,!is.na(mom3t_delivery_location))

#chart of Delivery location question at 2 week

DeliveryLocation_wk <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,inf2wk_delivery_location___1:inf2wk_delivery_location___5)%>%
  arrange(test_id,redcap_event_name)%>%
  rename("UFHealth"=inf2wk_delivery_location___1,
         "North Florida Regional"=inf2wk_delivery_location___2,
         "Birth & wellness Center of Gainesville"=inf2wk_delivery_location___3,
         "other"=inf2wk_delivery_location___4,
         "IDK"=inf2wk_delivery_location___5)%>%
  filter(redcap_event_name == "two_week_arm_1")%>%
  rename(participant=test_id,"visit type"=redcap_event_name)
kable(DeliveryLocation_wk)
#seperate variables and check for population 
uf<-DeliveryLocation_wk%>%
  select(participant,UFHealth)%>%
  filter(UFHealth>0)%>%
  select(participant)

NF<-DeliveryLocation_wk%>%
  select(participant,`North Florida Regional`)%>%
  filter(`North Florida Regional`>0)%>%
  select(participant)

BWC<-DeliveryLocation_wk%>%
  select(participant,`Birth & wellness Center of Gainesville`)%>%
  filter(`Birth & wellness Center of Gainesville`>0)%>%
  select(participant)

Other<-DeliveryLocation_wk%>%
  select(participant,`other`)%>%
  filter(other>0)%>%
  select(participant)

idk<-DeliveryLocation_wk%>%
  select(participant,`IDK`)%>%
  filter(IDK>0)%>%
  select(participant)

```

```{r}
#function for dynamic questions(Work in progress):

#test input
isAnswer(mom3t_insurance___1,mom3t_insurance___5,"Private health insurance","Medicaid","Some other kind of health insurance","I did not have any health insurance during the <i>month before</i> I got pregnant","IDK")


#function

# isAnswer<- function(x,a,b,c,d,e){
#   dynamic_variable <-ds_some_rows_v1%>%
#     select(test_id,redcap_event_name,x)%>%
#     arrange(test_id,redcap_event_name)%>%
#     filter(redcap_event_name="third_trimester_arm_1")
#   name<-c(a,b,c,d,e)
#   for(value in x){
#   dynamic_variable<-rename(name[value]=value)
# }
#   
#   dynamic_variable<-rename(participant=test_id,"visit type"=redcap_event_name)
#   
# one<-DeliveryLocation_wk%>%
#   select(participant,a)%>%
#   filter(a>0)%>%
#   select(participant)
# 
# two<-DeliveryLocation_wk%>%
#   select(participant,b)%>%
#   filter(b>0)%>%
#   select(participant)
# 
# three<-DeliveryLocation_wk%>%
#   select(participant,c)%>%
#   filter(c>0)%>%
#   select(participant)
# 
# four<-DeliveryLocation_wk%>%
#   select(participant,d)%>%
#   filter(d>0)%>%
#   select(participant)
# 
# five<-DeliveryLocation_wk%>%
#   select(participant,e)%>%
#   filter(e>0)%>%
#   select(participant)
#   
# tm1<-dplyr::full_join(one,two,three,by="participant")
# tm2<-dplyr::full_join(four, five,by="participant")
# kable(distinct(dplyr::full_join(tm1,tm2,by="participant")))
# }

```


## insurance responses from participants

###displays participants that responded to the question

```{r}
#chart of Delivery location question at 3rd trimester   
insurance <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,mom3t_insurance___1:mom3t_insurance___5)%>%
  arrange(test_id,redcap_event_name)%>%
  filter(redcap_event_name=="third_trimester_arm_1")%>%
  rename("Private health insurance"=mom3t_insurance___1,
         "Medicaid"=mom3t_insurance___2,
         "Some other kind of health insurance"=mom3t_insurance___3,
         "I did not have any health insurance during the <i>month before</i> I got pregnant"=mom3t_insurance___4,
         "IDK"=mom3t_insurance___5)%>%
  rename(participant=test_id,"visit type"=redcap_event_name)
kable(DeliveryLocation_tri)
#seperate variables and check for population 
one<-DeliveryLocation_wk%>%
  select(participant,UFHealth)%>%
  filter(UFHealth>0)%>%
  select(participant)

two<-DeliveryLocation_wk%>%
  select(participant,`North Florida Regional`)%>%
  filter(`North Florida Regional`>0)%>%
  select(participant)

three<-DeliveryLocation_wk%>%
  select(participant,`Birth & wellness Center of Gainesville`)%>%
  filter(`Birth & wellness Center of Gainesville`>0)%>%
  select(participant)

four<-DeliveryLocation_wk%>%
  select(participant,`other`)%>%
  filter(other>0)%>%
  select(participant)

five<-DeliveryLocation_wk%>%
  select(participant,`IDK`)%>%
  filter(IDK>0)%>%
  select(participant)

tm1<-dplyr::full_join(one,two,three,by="participant")
tm2<-dplyr::full_join(four, five,by="participant")
kable(distinct(dplyr::full_join(tm1,tm2,by="participant")))
```


### participants that didn't respond
```{r}
apple<-full_join(tm1,tm2,by="participant")%>%
  select(participant)%>%
  rename(test_id=participant)
  
kable(apple)
part<-ds_some_rows_v1%>%
  select(test_id)%>%
  distinct(test_id)
kable(part)
#isn't working as function intents.
#can't findout why setdiff() isn't working.
distinct<-setdiff(part, apple)
kable(distinct)


```