---
title: "Missing_infoV2"
author: "Luran M."
date: "June 18, 2019"
output: html_document
---

##Participants that will be looked at:

```{r echo=FALSE, results="hide", include=F}

library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)

#Create path to and api link to RedCaps
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)


# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)

# crc variables
#fields <- exportFieldNames(rcon)
#crc variables for 3rd trimester visit
desired_fields_triHU1=c("mom3t_breast_surg",
                       "mom3t_baby_sex",
                       "mom3t_prepreg_bmi",
                       "mom3t_folic",
                       "mom3t_preg_wks",
                       "mom3t_height_ft",
                       "mom3t_height_in",
                       "mom3t_prepreg_wt_lb",
                       "mom3t_bio_child",
                       "mom3t_diet",
                       "mom3t_exercise",
                       "mom3t_meds_regular",
                       "mom3t_diabetes",
                       "mom3t_bp",
                       "mom3t_depression",
                       "mom3t_med_hx",
                       "mom3t_dental",
                       "mom3t_healthy_wt",
                       "mom3t_vaccine",
                       "mom3t_dentist",
                       "mom3t_genetics",
                       "mom3t_medical_ctrl",
                       "mom3t_depression2",
                       "mom3t_infertility",
                       "mom3t_rx_safety",
                       "mom3t_smoke",
                       "mom3t_alcohol",
                       "mom3t_drugs",
                       "mom3t_asthma_3mo",
                       "mom3t_anemia_3mo",
                       "mom3t_heart_3mo",
                       "mom3t_epilepsy_3mo",
                       "mom3t_thyroid_3mo",
                       "mom3t_anxiety_3mo",
                       "mom3t_diabetes2",
                       "mom3t_high_bp",
                       "mom3t_depression3",
                       "mom3t_pos",
                       "mom3t_ovarian",
                       "mom3t_std",
                       "mom3t_preg_try",
                       "mom3t_stop_preg",
                       "mom3t_pnv_wks",
                       "mom3t_pnv_want",
                       "mom3t_pnv_apt",
                       "mom3t_pnv_insurance",
                       "mom3t_pnv_transport",
                       "mom3t_pnv_healthpln",
                       "mom3t_pnv_busy",
                       "mom3t_pnv_timeoff",
                       "mom3t_pnv_medicaid",
                       "mom3t_pnv_babysit",
                       "mom3t_pnv_preg_unknown",
                       "mom3t_pnv_preg_conf",
                       "mom3t_pnv_preg_unwant",
                       "mom3t_pnv_wtgain",
                    "mom3t_pnv_smoke",
                    "mom3t_pnv_bf",
                    "mom3t_pnv_alchohol",
                    "mom3t_pnv_meds",
                    "mom3t_pnv_drugs",
                    "mom3t_pnv_birth_defect",
                    "mom3t_pnv_preterm",
                    "mom3t_pnv_hiv",
                    "mom3t_pnv_abuse",
                    "mom3t_pnv_lead",
                    "mom3t_pnv_fishmerc",
                    "mom3t_pnv_fishmerc_lim",
                    "mom3t_pnv_hiv_test",
                    "mom3t_pnv_flushot",
                    "mom3t_pnv_flushot2",
                    "mom3t_pnv_tdap",
                    "mom3t_pnv_tdap_preg",
                    "mom3t_pnv_wic",
                    "mat3t_pnv_wic_bf",
                    "mom3t_pnv_depression",
                    "mom3t_pnv_gdm",
                    "mom3t_prenat_vagbleed",
                    "mom3t_uti",
                    "mom3t_nausea",
                    "mom3t_cervix",
                    "mom3t_high_bp2",
                    "mom3t_placenta",
                    "mom3t_labor_pains",
                    "mom3t_water_broke",
                    "mom3t_blood_trans",
                    "mom3t_car_accident",
                    "mom3t_preg_drinks1",
                    "mom3t_preg_drinks2",
                    "mom3t_preg_drinks3",
                    "mom3t_cigs_2yr",
                    "mom3t_preg_cigs1",
                    "mom3t_preg_cigs2",
                    "mom3t_preg_cigs3",
                    "mom3t_preg_cigs4",
                    "mom3t_cigs_now",
                    "mom3t_preg_smoke_hrs",
                    "mom3t_family_sick",
                    "mom3t_divorce",
                    "mom3t_moved",
                    "mom3t_homeless",
                    "mom3t_lostjob_partner",
                    "mom3t_lost_job",
                    "mom3t_job_hours",
                    "mom3t_military",
                    "mom3t_argued",
                    "mom3t_nopreg_partner",
                    "mom3t_rent",
                    "mom3t_jailtime",
                    "mom3t_alcoholism",
                    "mom3t_close_death",
                    "mom3t_partner_abuse_yr",
                    "mom3t_partner_abuse_preg",
                    "mom3t_language",
                    "mom3t_education",
                    "mom3t_birth_country",
                    "mom3t_income",
                    "mom3t_dependents",
                    "mom3t_dependents_2",
                    "mom3t_income_2",
                    "mom3t_infant_care",
                    "mom3t_infant_care_other",
                    "mom3t_hispanic",
                    "mom3t_baby_sex",
                    "mom3t_baby_hispanic")
desired_fields_triHU2=c("mom3t_delivery_location",
                        "mom3t_meds_rx_14d",
                        "mom3t_meds_name",
                        "mom3t_meds_length",
                        "mom3t_insurance",
                        "mom3t_insurance_other",
                        "mom3t_birth_ctrl",
                        "mom3t_birth_ctrl_other",
                        "mom3t_preg_no_reason",
                        "mom3t_preg_no_reason_other",
                        "mom3t_fertility_tr",
                        "mom3t_medical_tx_other",
                        "mom3t_preg_insur",
                        "mom3t_preg_insur_other",
                        "mom3t_baby_race","mom3t_race",
                        "mom3t_healthcare_services",
                        "mom3t_language_other",
                        "mom3t_country_other",
                        "mom3t_usa_yr")
# crc variables for the 2 week visit 
desired_fields_2wkHU=c("mom2wk_delivery_date",
                       "inf2wk_delivery_location",
                       "inf2wk_sex",
                       "mom2wk_baby_weight_pounds",
                       "inf2wk_baby_weight_today")

# combine desired fields and import test_id and redcap_event_name
desired_fields_all=c(desired_fields_triHU1,desired_fields_triHU2, "test_id","redcap_event_name")

# events to retain
#exportEvents(rcon)
events_to_retain  <- c("third_trimester_arm_1", "two_week_arm_1", "two_month_arm_1")

# list of instruments
#exportInstruments(rcon)
Instruments_to_retain <- c("health_update_3rd_trimester_v5082518","clinical_health_update_2wk_v4_042218",
                           "clinical_health_update_2mo_to_12mo_v3_022118","infant_feeding_questionnaire_2_weeks_v3_042218",
                           "infant_feeding_questionnaire_2mo_to_12mo_v3_022118")

# list of events
#exportEvents(rcon)

# list records
#exportRecords(rcon)

# export field names
#exportFieldNames(rcon)

# consented records
consent.records.v1=c("BLS001A","BLS002A","BLS003A")

# pull data
ds_some_rows_v1 <- redcap_read(
  batch_size=300,
  records= consent.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields_all,
  events     = events_to_retain,
  )$data

```

```{r echo=FALSE}
isAnswered1 <- function(dat,x){
  response <- dat%>%
    select(test_id,redcap_event_name,x)%>%
    arrange(test_id,redcap_event_name)%>%
    filter(redcap_event_name=="third_trimester_arm_1")%>%
    filter(is.na(x))%>%
    rename(participant=test_id,"visit"=redcap_event_name)
  if(dim(response)[1] != 0 ){
    response<- response%>%
      select(participant,x)
    kable(response)
}
}

```

## Did participant not respond to a third trimester questionare question:

### if no display, then all questions answered, otherwise a tables will be displayed showing the participant and the question variable that was answered.

---------------------------------------------------

```{r}
for(value in desired_fields_triHU1){
  isAnswered1(ds_some_rows_v1,value)
}

```

## Was delivery location told by participant?

### (displays both 2-week response chart and if the question was answered in either questionare)

-------------------------------------------------

```{r echo=FALSE}


#chart of Delivery location question at 3rd trimester   
DeliveryLocation_tri <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,mom3t_delivery_location)%>%
  arrange(test_id,redcap_event_name)%>%
  filter(redcap_event_name == "third_trimester_arm_1")


#Talbe of participants who responsed to the question

DeliveryLocation_tri_pop<-filter(DeliveryLocation_tri,!is.na(mom3t_delivery_location))

#chart of Delivery location question at 2 week

DeliveryLocation_wk <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,inf2wk_delivery_location___1:inf2wk_delivery_location___5)%>%
  arrange(test_id,redcap_event_name)%>%
  rename("UFHealth"=inf2wk_delivery_location___1,
         "North Florida Regional"=inf2wk_delivery_location___2,
         "Birth & wellness Center of Gainesville"=inf2wk_delivery_location___3,
         "other"=inf2wk_delivery_location___4,
         "IDK"=inf2wk_delivery_location___5)%>%
  filter(redcap_event_name == "two_week_arm_1")%>%
  rename(participant=test_id,"visit type"=redcap_event_name)
kable(DeliveryLocation_wk)
#seperate variables and check for population 
uf<-DeliveryLocation_wk%>%
  select(participant,UFHealth)%>%
  filter(UFHealth>0)%>%
  select(participant)

NF<-DeliveryLocation_wk%>%
  select(participant,`North Florida Regional`)%>%
  filter(`North Florida Regional`>0)%>%
  select(participant)

BWC<-DeliveryLocation_wk%>%
  select(participant,`Birth & wellness Center of Gainesville`)%>%
  filter(`Birth & wellness Center of Gainesville`>0)%>%
  select(participant)

Other<-DeliveryLocation_wk%>%
  select(participant,`other`)%>%
  filter(other>0)%>%
  select(participant)

idk<-DeliveryLocation_wk%>%
  select(participant,`IDK`)%>%
  filter(IDK>0)%>%
  select(participant)

```

### participants that responded:

-------------------------------------------------

```{r echo=FALSE}
#recombine variables and show distinct population 
tm1<-dplyr::full_join(uf,NF,BWC,by="participant")
tm2<-dplyr::full_join(idk,Other,by="participant")
kable(distinct(dplyr::full_join(tm1,tm2,by="participant")))

```

