---
title: "Participant Dropout"
author: "Luran M."
date: "July 10, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)

#Create path to and api link to RedCaps
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)


# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)

# crc variables
#fields <- exportFieldNames(rcon)
#crc variables for Looking at dropped participants 

desired_fields_dropped=c("beach_part_drop_out","beach_drop_reason","beach_last_visit","mom2wk_mod","mom3t_prepreg_bmi","inf2wk_delivery_location","mom3t_delivery_location")
# combine desired fields and import test_id and redcap_event_name
desired_fields_all=c(desired_fields_dropped,"test_id","redcap_event_name")

# events to retain
#exportEvents(rcon)
events_to_retain  <- c("third_trimester_arm_1", "two_week_arm_1", "two_month_arm_1")

# list of instruments
#exportInstruments(rcon)
Instruments_to_retain <- c("health_update_3rd_trimester_v5082518","clinical_health_update_2wk_v4_042218",
                           "clinical_health_update_2mo_to_12mo_v3_022118","infant_feeding_questionnaire_2_weeks_v3_042218",
                           "infant_feeding_questionnaire_2mo_to_12mo_v3_022118")

# list of events
#exportEvents(rcon)

# list records
#exportRecords(rcon)

# export field names
#exportFieldNames(rcon)

# consented records
consent.records.v1=c("BLS006A","BLS010A","BLS015A","BLS026A","BLS029A","BLS037A","BLS039A","BLS050A","BLS054A","BLS001A")

# pull data
ds_some_rows_v1 <- redcap_read(
  batch_size=300,
  records= consent.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields_all,
  events     = events_to_retain,
  )$data

head(ds_some_rows_v1)
```

##Participants that have dropped:
```{r echo=FALSE}
participants_dropped<-ds_some_rows_v1%>%
  select(test_id,beach_part_drop_out)%>%
  filter(beach_part_drop_out==1)%>%
  distinct(test_id)
participant_dropped<-participants_dropped%>%
  select(test_id)%>%
  rename("participants"=test_id)
kable(participant_dropped)
```

##Last visit completed by each participant:
```{r echo=FALSE}
last_visit<-ds_some_rows_v1%>%
  select(test_id,beach_part_drop_out,beach_last_visit)%>%
  filter(beach_part_drop_out==1)
  
for(i in 1:nrow(last_visit)){
  cat(last_visit[i,1])
  if(last_visit[i,2]==1)
    cat("\tlast visit : third trimester\n")
  else if(last_visit[i,2]==2)
    cat("\tlast visit : 2 week\n")
  else if(last_visit[i,2]==3)
    cat("\tlast visit : 2 month\n")
  else if(last_visit[i,2]==2)
    cat("\tlast visit : 6 month\n")
  else if(last_visit[i,2]==2)
    cat("\tlast visit : 12 month\n")
}

```

##Mode of delivery for participant:

```{r echo=FALSE}
test<-ds_some_rows_v1%>%
  select(test_id,beach_part_drop_out)%>%
  filter(beach_part_drop_out==1)%>%
  distinct(test_id)

apple<-c()
for(i in 1:nrow(test)){
  apple<-c(apple,test[i,1])
}

mode_delevery<-ds_some_rows_v1%>%
  select(test_id,beach_part_drop_out,beach_last_visit, mom2wk_mod)%>%
  filter(test_id%in%apple)%>%
  select(test_id,mom2wk_mod)


for(i in 1:nrow(mode_delevery)){
  cat(mode_delevery[i,1])
  if(is.na(mode_delevery[i,2]))
    cat("\tDid not respond as to mode of delivery\n")
  else if(mode_delevery[i,2]==1)
    cat("\tlast visit : 2 week\n")
  else if(mode_delevery[i,2]==2)
    cat("\tlast visit : 2 month\n")
}

```

##Pre-pregnant BMI of dropped participants:
```{r echo=FALSE}
BMI <- ds_some_rows_v1%>%
  select(test_id,mom3t_prepreg_bmi)%>%
  filter(test_id%in%apple)%>%
  rename("participant"=test_id,"pre-Pregnant BMI"=mom3t_prepreg_bmi)
kable(BMI)

```

##Delivery Location of dropped participants:
###If empty, then dropped participant didn't provide location
```{r echo=FALSE}

#chart of Delivery location question at 3rd trimester   
DeliveryLocation_tri <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,mom3t_delivery_location)%>%
  arrange(test_id,redcap_event_name)%>%
  filter(redcap_event_name == "third_trimester_arm_1")


#Talbe of participants who responsed to the question

DeliveryLocation_tri_pop<-filter(DeliveryLocation_tri,!is.na(mom3t_delivery_location))

#chart of Delivery location question at 2 week

DeliveryLocation_wk <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,inf2wk_delivery_location___1:inf2wk_delivery_location___5,beach_part_drop_out)%>%
  arrange(test_id,redcap_event_name)%>%
  rename("UFHealth"=inf2wk_delivery_location___1,
         "North Florida Regional"=inf2wk_delivery_location___2,
         "Birth & wellness Center of Gainesville"=inf2wk_delivery_location___3,
         "other"=inf2wk_delivery_location___4,
         "IDK"=inf2wk_delivery_location___5)%>%
  filter(redcap_event_name == "two_week_arm_1",test_id%in%apple)%>%
  rename(participant=test_id,"visit type"=redcap_event_name)
kable(DeliveryLocation_wk)
#seperate variables and check for population 

uf<-DeliveryLocation_wk%>%
  select(participant,UFHealth)%>%
  filter(UFHealth>0)%>%
  select(participant)

NF<-DeliveryLocation_wk%>%
  select(participant,`North Florida Regional`)%>%
  filter(`North Florida Regional`>0)%>%
  select(participant)

BWC<-DeliveryLocation_wk%>%
  select(participant,`Birth & wellness Center of Gainesville`)%>%
  filter(`Birth & wellness Center of Gainesville`>0)%>%
  select(participant)

Other<-DeliveryLocation_wk%>%
  select(participant,`other`)%>%
  filter(other>0)%>%
  select(participant)

idk<-DeliveryLocation_wk%>%
  select(participant,`IDK`)%>%
  filter(IDK>0)%>%
  select(participant)

tm1<-dplyr::full_join(uf,NF,BWC,by="participant")
tm2<-dplyr::full_join(Other, idk,by="participant")
#kable(distinct(dplyr::full_join(tm1,tm2,by="participant")))
```