---
title: "Facebook Ad- April 2018"
author: "Dominick Lemas"
date: "May 8, 2018"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library
library(readxl)
library(data.table)
library(tidyr)
library(dplyr)
library(ggplot2)

# Computer
  location="djlemas"
# location="Dominick";location
  
# Directory
work.dir=paste("C:\\Users\\",location,"\\Dropbox (UFL)\\02_Projects\\BEACH_STUDY\\01_Recruitment\\facebook\\data\\",sep="")
data.dir=paste("C:\\Users\\",location,"\\Dropbox (UFL)\\02_Projects\\BEACH_STUDY\\01_Recruitment\\facebook\\data\\",sep="")
out.dir=paste("C:\\Users\\",location,"\\Dropbox (UFL)\\02_Projects\\BEACH_STUDY\\01_Recruitment\\facebook\\table\\",sep="")

# Set Working Directory
setwd(work.dir)
# list.files()

# file parameters
n_max=10000
data.file.name="BEACH Report 3-23-18 to 4-13-18.xlsx"

# read data
# day of week
#------------
day.dat=read_xlsx(paste(data.dir,data.file.name,sep=""), sheet = "Results by Day of Week", range = NULL, col_names = TRUE,
                   col_types = NULL, na = "NA", trim_ws = TRUE, skip = 0, n_max = Inf,
                   guess_max = min(1000, n_max))

# rename data
dat=day.dat

# rename variables
newdata=rename(dat, reporting_starts = `Reporting Starts`, reporting_ends=`Reporting Ends`, ad_set_name='Ad Set Name', 
               delivery=Delivery, results=`Results`, result_indicator=`Result Indicator`, reach=Reach,
               impressions=Impressions, cost_per_results='Cost per Results', budget=Budget,
               budget_type='Budget Type', amount_spent_USD='Amount Spent (USD)', ends=Ends,
               frequency=Frequency, unique_link_clicks='Unique Link Clicks',
               button_clicks='Button Clicks')

# compute "day of week" variables
newdata$weekday=weekdays(as.Date(newdata$reporting_ends,'%Y-%m-%d',tz = "UTC"))

# day of week
#------------
time.dat=read_xlsx(paste(data.dir,data.file.name,sep=""), sheet = "Results by Time of Day", range = NULL, col_names = TRUE,
                   col_types = NULL, na = "NA", trim_ws = TRUE, skip = 0, n_max = Inf,
                   guess_max = min(1000, n_max))

# rename data
dat2=time.dat

# rename variables
newdata.time=rename(dat2, reporting_starts = `Reporting Starts`, reporting_ends=`Reporting Ends`, ad_set_name='Ad Set Name', 
               delivery=Delivery, results=`Results`, result_indicator=`Result Indicator`, reach=Reach,
               impressions=Impressions, cost_per_results='Cost per Results', budget=Budget,
               budget_type='Budget Type', amount_spent_USD='Amount Spent (USD)', ends=Ends,
               frequency=Frequency, unique_link_clicks='Unique Link Clicks',
               button_clicks='Button Clicks')

```

## What day of week did people click on the ad?


```{r echo=FALSE, message = FALSE}

# select and compute variables
dat.days=newdata %>%
  select(weekday,unique_link_clicks,button_clicks,cost_per_results) %>%
  group_by(weekday) %>%
  summarize(click.m=mean(unique_link_clicks),
            button.m=mean(button_clicks),
            cost.m=mean(cost_per_results)) %>%
  mutate(weekday.c = factor(weekday, levels = c("Sunday","Monday","Tuesday","Wednesday",
                                                "Thursday","Friday","Saturday")))
# plot: click.m 
ggplot(dat.days, aes(x=factor(weekday.c), y=click.m))+geom_bar(stat="identity")

```

## What times of day did people click on ad?



```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
